-- filepath: src/main/resources/META-INF/load.sql

-- DDL: Create tables for each entity (JPA will use these table names)
-- Note: Using DROP TABLE IF EXISTS and CREATE TABLE for Derby compatibility

-- 1. BENUTZERENTITY (SINGLE_TABLE inheritance for Admin, Kundenservice, MitarbeiterKreditvergabe)

CREATE TABLE BENUTZERENTITY (
  BENUTZERNAME      VARCHAR(50)   PRIMARY KEY,
  PASSWORT          VARCHAR(100),
  NAME              VARCHAR(100),
  TELEFONNUMMER     VARCHAR(20),
  ROLLE             VARCHAR(50),
  USER_TYPE         VARCHAR(50),   -- discriminator: ADMIN, KUNDENSERVICE, KREDITVERGABE
  MITARBEITER_ID    VARCHAR(50),   -- only for KREDITVERGABE
  ABTEILUNG         VARCHAR(100)   -- only for KREDITVERGABE
);

-- 2. KUNDEENTITY

CREATE TABLE KUNDEENTITY (
  KUNDENNUMMER      VARCHAR(20)   PRIMARY KEY,
  NAME              VARCHAR(100),
  ADRESSE           VARCHAR(255),
  KUNDENSTATUS      VARCHAR(50),
  GEBURTSDATUM      DATE,
  TELEFONNUMMER     VARCHAR(20),
  EMAIL             VARCHAR(100)
);

-- 3. BANKKONTOENTITY

CREATE TABLE BANKKONTOENTITY (
  IBAN                     VARCHAR(34)   PRIMARY KEY,
  KONTOART                 VARCHAR(50),
  KONTOSTAND               DOUBLE,
  KONTOEROEFFNUNGSDATUM    DATE,
  KONTOSTATUS              VARCHAR(50),
  BESITZER_KUNDENNUMMER    VARCHAR(20),
  CONSTRAINT FK_BANKKONTO_KUNDE FOREIGN KEY (BESITZER_KUNDENNUMMER)
    REFERENCES KUNDEENTITY(KUNDENNUMMER)
);

-- 4. KREDITANTRAGENTITY

CREATE TABLE KREDITANTRAGENTITY (
  KREDITANTRAGSNUMMER   BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  KREDITSUMME           DOUBLE,
  LAUFZEIT              VARCHAR(50),
  ZINS                  DOUBLE,
  STATUS                VARCHAR(20),
  KUNDE_ID              VARCHAR(20),
  CONSTRAINT FK_KREDITANTRAG_KUNDE FOREIGN KEY (KUNDE_ID)
    REFERENCES KUNDEENTITY(KUNDENNUMMER)
);

-- 5. TRANSAKTIONENTITY

CREATE TABLE TRANSAKTIONENTITY (
  TRANSAKTIONSNUMMER    VARCHAR(50)   PRIMARY KEY,
  BANKKONTO_IBAN        VARCHAR(34),
  EMPFAENGER            VARCHAR(100),
  BETRAG                DOUBLE,
  TRANSAKTIONSDATUM     DATE,
  TRANSAKTIONSSTATUS    VARCHAR(20),
  TRANSAKTIONSART       VARCHAR(20),
  CONSTRAINT FK_TRANSAKTION_BANKKONTO FOREIGN KEY (BANKKONTO_IBAN)
    REFERENCES BANKKONTOENTITY(IBAN)
);


-- DML: Insert example values

-- BENUTZERENTITY
INSERT INTO BENUTZERENTITY (USER_TYPE, BENUTZERNAME, NAME, PASSWORT, TELEFONNUMMER, ROLLE)
  VALUES ('ADMIN', 'admin', 'Administrator', 'adminpass', '0123456789', 'ADMIN');
INSERT INTO BENUTZERENTITY (USER_TYPE, BENUTZERNAME, NAME, PASSWORT, TELEFONNUMMER, ROLLE)
  VALUES ('KUNDENSERVICE', 'service01', 'Sarah Schmidt', 'servicepass', '0987654321', 'KUNDENSERVICE');
INSERT INTO BENUTZERENTITY (USER_TYPE, BENUTZERNAME, NAME, PASSWORT, TELEFONNUMMER, ROLLE, MITARBEITER_ID, ABTEILUNG)
  VALUES ('KREDITVERGABE', 'credit01', 'Peter Meier', 'creditpass', '01122334455', 'KREDITVERGABE', 'MK-789', 'Credit Department');

-- KUNDEENTITY
INSERT INTO KUNDEENTITY (KUNDENNUMMER, NAME, ADRESSE, KUNDENSTATUS, GEBURTSDATUM, TELEFONNUMMER, EMAIL)
  VALUES ('K-001', 'Max Mustermann', 'Musterstraße 1, 12345 Musterstadt', 'ACTIVE', '1985-05-20', '01511234567', 'max.mustermann@example.com');
INSERT INTO KUNDEENTITY (KUNDENNUMMER, NAME, ADRESSE, KUNDENSTATUS, GEBURTSDATUM, TELEFONNUMMER, EMAIL)
  VALUES ('K-002', 'Erika Mustermann', 'Beispielweg 2, 54321 Beispielhausen', 'ACTIVE', '1990-11-15', '01607654321', 'erika.mustermann@example.com');

-- BANKKONTOENTITY
INSERT INTO BANKKONTOENTITY (IBAN, KONTOART, KONTOSTAND, KONTOEROEFFNUNGSDATUM, KONTOSTATUS, BESITZER_KUNDENNUMMER)
  VALUES ('DE89370400440532013000', 'Girokonto', 1500.75, '2020-01-10', 'ACTIVE', 'K-001');
INSERT INTO BANKKONTOENTITY (IBAN, KONTOART, KONTOSTAND, KONTOEROEFFNUNGSDATUM, KONTOSTATUS, BESITZER_KUNDENNUMMER)
  VALUES ('DE02100100100123456789', 'Sparkonto', 12500.00, '2021-03-15', 'ACTIVE', 'K-001');
INSERT INTO BANKKONTOENTITY (IBAN, KONTOART, KONTOSTAND, KONTOEROEFFNUNGSDATUM, KONTOSTATUS, BESITZER_KUNDENNUMMER)
  VALUES ('DE27100777770200283700', 'Girokonto', -250.50, '2019-08-01', 'ACTIVE', 'K-002');

-- KREDITANTRAGENTITY (Note: KREDITANTRAGSNUMMER is auto-generated, so we don't specify it)
INSERT INTO KREDITANTRAGENTITY (KREDITSUMME, LAUFZEIT, ZINS, STATUS, KUNDE_ID)
  VALUES (10000.00, '48 Monate', 3.50, 'PENDING', 'K-002');

-- TRANSAKTIONENTITY (Note: foreign key column name is BANKKONTO_IBAN)
INSERT INTO TRANSAKTIONENTITY (TRANSAKTIONSNUMMER, BANKKONTO_IBAN, EMPFAENGER, BETRAG, TRANSAKTIONSDATUM, TRANSAKTIONSSTATUS, TRANSAKTIONSART)
  VALUES ('TXN-001', 'DE89370400440532013000', 'Stromversorger GmbH', 85.50, '2025-06-01', 'COMPLETED', 'AUSGANG');
INSERT INTO TRANSAKTIONENTITY (TRANSAKTIONSNUMMER, BANKKONTO_IBAN, EMPFAENGER, BETRAG, TRANSAKTIONSDATUM, TRANSAKTIONSSTATUS, TRANSAKTIONSART)
  VALUES ('TXN-002', 'DE89370400440532013000', 'Arbeitgeber AG', 2800.00, '2025-05-30', 'COMPLETED', 'EINGANG');
INSERT INTO TRANSAKTIONENTITY (TRANSAKTIONSNUMMER, BANKKONTO_IBAN, EMPFAENGER, BETRAG, TRANSAKTIONSDATUM, TRANSAKTIONSSTATUS, TRANSAKTIONSART)
  VALUES ('TXN-003', 'DE27100777770200283700', 'Miete', 750.00, '2025-06-01', 'COMPLETED', 'AUSGANG');
